<a href="https://colab.research.google.com/github/ritwiks9635/Unsupervised_Learning_projects/blob/main/Collaborative_based_Filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Book Recommendation System ðŸ“šðŸ“šðŸ“šðŸ“•ðŸ“˜ðŸ“—ðŸ“šðŸ“’ðŸ“”ðŸ““ðŸ“–ðŸ“– Using Collaborative-based Filtering***

In [2]:
! unzip /content/https:/www.kaggle.com/datasets/arashnic/book-recommendation-dataset/book-recommendation-dataset.zip

Archive:  /content/https:/www.kaggle.com/datasets/arashnic/book-recommendation-dataset/book-recommendation-dataset.zip
  inflating: Books.csv
  inflating: Ratings.csv
  inflating: Users.csv
  inflating: recsys_taxonomy2.png

In [3]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [4]:
books = pd.read_csv("Books.csv")
rating = pd.read_csv("Ratings.csv")
users = pd.read_csv("Users.csv")

In [5]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [6]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [7]:
rating.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [8]:
books = books[["ISBN", "Book-Title", "Book-Author", "Year-Of-Publication", "Publisher"]]
books.rename(columns = {'Book-Title' : 'title', 'Book-Author' : 'author', 'Year-Of-Publication': 'year', 'Publisher' : 'publish'}, inplace=True)

In [9]:
books.head()

,ISBN,title,author,year,publish
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company

In [10]:
print("books shape ::", books.shape)
print("users shape ::", users.shape)
print("rating shape ::", rating.shape)

books shape :: (271360, 5)
users shape :: (278858, 3)
rating shape :: (1149780, 3)

In [11]:
x =  rating['User-ID'].value_counts() > 200
user_value = x[x].index
user_value.shape

(899,)

In [12]:
ratings = rating[rating["User-ID"].isin(user_value)]

In [13]:
ratings

         User-ID        ISBN  Book-Rating
1456      277427  002542730X           10
1457      277427  0026217457            0
1458      277427  003008685X            8
1459      277427  0030615321            0
1460      277427  0060002050            0
...          ...         ...          ...
1147612   275970  3829021860            0
1147613   275970  4770019572            0
1147614   275970   896086097            0
1147615   275970  9626340762            8
1147616   275970  9626344990            0

[526356 rows x 3 columns]

In [14]:
books_rating = ratings.merge(books, on = "ISBN")
books_rating.rename(columns = {"Book-Rating" : "rating"}, inplace=True)

In [15]:
n_ratings = books_rating.groupby("title")["rating"].count().reset_index()
n_ratings.rename(columns = {"rating" : "n_ratings"}, inplace=True)

In [16]:
n_ratings.head()

                                               title  n_ratings
0   A Light in the Storm: The Civil War Diary of ...          2
1                              Always Have Popsicles          1
2               Apple Magic (The Collector's series)          1
3   Beyond IBM: Leadership Marketing and Finance ...          1
4   Clifford Visita El Hospital (Clifford El Gran...          1

In [17]:
final_data = books_rating.merge(n_ratings, on = "title")

In [18]:
final_data

,User-ID,ISBN,rating,title,author,year,publish,n_ratings
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
1,3363,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
2,11676,002542730X,6,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
3,12538,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
4,13552,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
...,...,...,...,...,...,...,...,...
487666,275970,1892145022,0,Here Is New York,E. B. White,1999,Little Bookroom,1
487667,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA),1
487668,275970,3411086211,10,Die Biene.,Sybil GrÃƒ?Ã‚Â¤fin SchÃƒ?Ã‚Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",1
487669,275970,3829021860,0,The Penis Book,Joseph Cohen,1999,Konemann,1
487670,275970,4770019572,0,Musashi,Eiji Yoshikawa,1995,Kodansha International (JPN),1

In [19]:
final_ratings = final_data[final_data["n_ratings"] >=50]

In [26]:
final_ratings.drop_duplicates(['User-ID','title'], inplace=True)

In [27]:
final_ratings.shape

(59850, 8)

In [51]:
pivot_rating = final_ratings.pivot_table(columns = "User-ID", index = "title", values = "rating")

In [52]:
pivot_rating.fillna(0, inplace=True)

In [32]:
pivot_rating

User-ID,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [47]:
from scipy.sparse import csr_matrix
sparse_rating = csr_matrix(pivot_rating)

In [48]:
print(sparse_rating)

  (0, 0)	9.0
  (0, 16)	8.0
  (0, 37)	9.0
  (0, 42)	8.0
  (0, 59)	7.0
  (0, 135)	9.0
  (0, 156)	10.0
  (0, 170)	9.0
  (0, 187)	8.0
  (0, 220)	10.0
  (0, 221)	10.0
  (0, 245)	10.0
  (0, 277)	10.0
  (0, 359)	10.0
  (0, 370)	9.0
  (0, 389)	10.0
  (0, 477)	9.0
  (0, 491)	7.0
  (0, 507)	9.0
  (0, 554)	10.0
  (0, 604)	9.0
  (0, 611)	8.0
  (0, 695)	9.0
  (0, 734)	9.0
  (0, 762)	8.0
  :	:
  (740, 484)	8.0
  (740, 681)	9.0
  (741, 16)	8.0
  (741, 26)	7.0
  (741, 86)	10.0
  (741, 111)	5.0
  (741, 150)	6.0
  (741, 233)	7.0
  (741, 290)	8.0
  (741, 303)	9.0
  (741, 322)	10.0
  (741, 367)	10.0
  (741, 384)	9.0
  (741, 446)	7.0
  (741, 450)	9.0
  (741, 485)	7.0
  (741, 498)	10.0
  (741, 505)	8.0
  (741, 544)	10.0
  (741, 592)	8.0
  (741, 700)	10.0
  (741, 713)	8.0
  (741, 745)	10.0
  (741, 830)	9.0
  (741, 880)	8.0

In [37]:
from sklearn.neighbors import NearestNeighbors

In [40]:
NN = NearestNeighbors(algorithm = "brute")

In [49]:
NN.fit(sparse_rating)

NearestNeighbors(algorithm='brute')

In [68]:
Distance, suggestion = NN.kneighbors(pivot_rating.iloc[320,:].values.reshape(1,-1))

In [75]:
suggestion

array([[320, 372, 184, 311, 308]])

In [77]:
for i in range(len(suggestion)):
  print(pivot_rating.index[suggestion[i]])

Index(['Long After Midnight', 'No Safe Place', 'Exclusive',
       'Last Man Standing', 'Lake Wobegon days'],
      dtype='object', name='title')

In [78]:
Distance, suggestion = NN.kneighbors(pivot_rating.iloc[237,:].values.reshape(1,-1))

In [79]:
for i in range(len(suggestion)):
  print(pivot_rating.index[suggestion[i]])

Index(['Harry Potter and the Chamber of Secrets (Book 2)',
       'Harry Potter and the Prisoner of Azkaban (Book 3)',
       'Harry Potter and the Goblet of Fire (Book 4)',
       'Harry Potter and the Sorcerer's Stone (Book 1)', 'Exclusive'],
      dtype='object', name='title')

In [80]:
def suggestion_book(user_id):
  _, suggestion = NN.kneighbors(pivot_rating.iloc[user_id,:].values.reshape(1,-1))
  for i in range(len(suggestion)):
    print(pivot_rating.index[suggestion[i]])

In [81]:
suggestion_book(237)

Index(['Harry Potter and the Chamber of Secrets (Book 2)',
       'Harry Potter and the Prisoner of Azkaban (Book 3)',
       'Harry Potter and the Goblet of Fire (Book 4)',
       'Harry Potter and the Sorcerer's Stone (Book 1)', 'Exclusive'],
      dtype='object', name='title')

In [82]:
suggestion_book(320)

Index(['Long After Midnight', 'No Safe Place', 'Exclusive',
       'Last Man Standing', 'Lake Wobegon days'],
      dtype='object', name='title')